In [2]:
import numpy as np

In [3]:
def print_attributes(tensor):
    print("Number of axes (rank): %d" % tensor.ndim)
    print("Shape: %s" % str(tensor.shape))
    print("Data type: %s" % str(tensor.dtype))

In [4]:
scalar = np.array(12)
print_attributes(scalar)

Number of axes (rank): 0
Shape: ()
Data type: int64


In [5]:
vector = np.array([12.0, 3.0, 6.0, 14.0])
print_attributes(vector)

Number of axes (rank): 1
Shape: (4,)
Data type: float64


In [6]:
matrix = np.array([[5, 78, 2, 34, 0], [6, 79, 3, 35, 1], [7, 80, 4, 36, 2]])
print_attributes(matrix)

Number of axes (rank): 2
Shape: (3, 5)
Data type: int64


In [7]:
#slicing
matrix[0]

array([ 5, 78,  2, 34,  0])

In [8]:
#slicing
matrix[1:3]

array([[ 6, 79,  3, 35,  1],
       [ 7, 80,  4, 36,  2]])

In [9]:
#slicing
matrix[1:3, 1:3]

array([[79,  3],
       [80,  4]])

In [10]:
#slicing
matrix[:, 0:-4]

array([[5],
       [6],
       [7]])

In [14]:
matrix.reshape(1,15)

array([[ 5, 78,  2, 34,  0,  6, 79,  3, 35,  1,  7, 80,  4, 36,  2]])

In [ ]:
def load_data():
    import pandas as pd
    from dao import InvestDao
    
    dao = InvestDao()

    rows = dao.sql("SELECT * FROM features_data")
    return rows

In [ ]:
fd = np.array(load_data())

In [ ]:
train_data = fd[:,1:-1].astype(int)
print_attributes(train_data)

In [ ]:
train_labels = fd[:,-1].astype(int)
print_attributes(train_labels)